default:
    api_login_id: 6ZqUc56q
    api_transaction_key: 92bbPV487mh8GguL
    merchant_hash_value: 6ZqUc56q
    gateway: :test
production:
    api_login_id: 9CYgR5yLJB6V
    api_transaction_key: 997KbVJsBw6G59LN
    merchant_hash_value: 
    gateway: :live
development:
  
test:

staging:


